[project]
name = "src"
version = "0.0.1"
description = "Flight Price Prediction MLOps Project"
authors = [{name = "Shreyank Kasable", email = "shreyankkasabale@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
